name: Protect main branch
enforcement: active
conditions:
  ref_name:
    include:
      - main
rules:
  - type: pull_request
    parameters:
      required_approving_review_count: 1
      dismiss_stale_reviews_on_push: true
      require_code_owner_review: true
  - type: required_status_checks
    parameters:
      strict_required_status_checks_policy: true
      required_status_checks: []
  - type: non_fast_forward
